# Generated by Django 3.0.4 on 2020-05-30 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='not_selected', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CODCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CODCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='not_selected', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CODDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Detail', max_length=100, verbose_name='Detail name')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Number of products')),
                ('whose_material', models.CharField(choices=[('Author', 'Author'), ('Offeror', 'Offeror')], default='Offeror', max_length=10, verbose_name='Whose material?')),
                ('Note', models.TextField(default='You Note', verbose_name='You Note')),
                ('Deadline', models.DateField(null=True, verbose_name='Deadline')),
                ('Availability_date', models.DateField(null=True, verbose_name='Availability date')),
                ('image_cover', models.ImageField(default='COD_Detail_image_cover/default.jpg', upload_to='COD_Detail_image_cover', verbose_name='Cover image')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='COD_detail_files', verbose_name='PDF')),
                ('dxf', models.FileField(blank=True, null=True, upload_to='COD_detail_files', verbose_name='DXF')),
                ('step', models.FileField(blank=True, null=True, upload_to='COD_detail_files', verbose_name='STEP')),
                ('part', models.FileField(blank=True, null=True, upload_to='COD_detail_files', verbose_name='PART')),
                ('Categories', models.ManyToManyField(blank=True, default='Default', related_name='CODDetail', to='orders.CODCategories', verbose_name='Categories')),
            ],
        ),
        migrations.CreateModel(
            name='CODMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MassOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('other_files', models.FileField(upload_to='MassOrderArchive', verbose_name='Archive')),
                ('title', models.CharField(default='Headline', max_length=100, verbose_name='Headline')),
                ('description', models.TextField(default='Description Order', verbose_name='Description Order')),
                ('lead_time', models.DateField(default=django.utils.timezone.now, verbose_name='Deadline')),
                ('proposed_budget', models.CharField(choices=[('Unknown', 'Unknown'), ('Small, less than $ 100', 'Small, less than $ 100'), ('Medium, less than $ 1000', 'Medium, less than $ 1000'), ('High, over $ 1000', 'High, over $ 1000')], default='Unknown', max_length=40, verbose_name='Budget')),
                ('activity', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('In discussion', 'In discussion'), ('In work', 'In work'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='In discussion', max_length=20, verbose_name='Order status')),
                ('crushed_order', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.AllCity', verbose_name='Order City')),
            ],
        ),
        migrations.CreateModel(
            name='OperationCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='Headline', max_length=100, verbose_name='Headline')),
                ('description', models.TextField(default='Description Order', verbose_name='Description Order')),
                ('pdf_view', models.FileField(default='default.pdf', upload_to='pdf', verbose_name='Pdf order cover')),
                ('image_view', models.ImageField(default='default.jpg', upload_to='image_preview', verbose_name='Cover image')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Number of products')),
                ('lead_time', models.DateField(default=django.utils.timezone.now, verbose_name='Deadline')),
                ('proposed_budget', models.CharField(choices=[('Unknown', 'Unknown'), ('Small, less than $ 100', 'Small, less than $ 100'), ('Medium, less than $ 1000', 'Medium, less than $ 1000'), ('High, over $ 1000', 'High, over $ 1000')], default='Unknown', max_length=40, verbose_name='Budget')),
                ('activity', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('In discussion', 'In discussion'), ('In work', 'In work'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='In discussion', max_length=20, verbose_name='Order status')),
                ('group_order', models.BooleanField(default=False, verbose_name='Group?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, default='Default', related_name='orders', to='orders.OperationCategories', verbose_name='Categories')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.AllCity', verbose_name='Order City')),
                ('mass_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.MassOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('offer_description', models.TextField(verbose_name='Offer Description')),
                ('deadline', models.DateTimeField(verbose_name='Production time')),
                ('offer_price', models.PositiveIntegerField(verbose_name='Suggested price')),
                ('status', models.CharField(choices=[('In discussion', 'In discussion'), ('In work', 'In work'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='In discussion', max_length=20, verbose_name='Offer Status')),
                ('selected_offer', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='GroupSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('offer_description', models.TextField(verbose_name='Offer Description')),
                ('deadline', models.DateTimeField(verbose_name='Production time')),
                ('offer_price', models.PositiveIntegerField(verbose_name='Suggested price')),
                ('status', models.CharField(choices=[('In discussion', 'In discussion'), ('In work', 'In work'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='In discussion', max_length=20, verbose_name='Offer Status')),
                ('selected_offer', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('mass_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.MassOrder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='COD_detail_files', verbose_name='File')),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.CODDetail')),
            ],
            options={
                'verbose_name': 'Files',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(default=django.utils.timezone.now)),
                ('feet', models.TextField()),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Suggestion')),
            ],
        ),
        migrations.CreateModel(
            name='CODOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='Headline', max_length=100, verbose_name='Headline')),
                ('description', models.TextField(default='Description Order', verbose_name='Description Order')),
                ('group_status', models.BooleanField(default=False, verbose_name='Group Status')),
                ('archive', models.FileField(null=True, upload_to='COD_order_archive', verbose_name='Group Order Archive')),
                ('table', models.FileField(null=True, upload_to='COD_order_tables')),
                ('pdf_cover', models.FileField(default='default.pdf', upload_to='COD_order_pdf_cover', verbose_name='Pdf order cover')),
                ('image_cover', models.ImageField(default='default.jpg', upload_to='COD_order_image_cover', verbose_name='Cover image')),
                ('proposed_budget', models.CharField(choices=[('Unknown', 'Unknown'), ('Small', 'Small'), ('Medium', 'Medium'), ('High', 'High')], default='Unknown', max_length=40, verbose_name='Budget')),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Discussion', 'Discussion'), ('InWork', 'InWork'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Created', max_length=20, verbose_name='Order status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.CODCity', verbose_name='Order City')),
            ],
        ),
        migrations.CreateModel(
            name='CODFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='COD_detail_files', verbose_name='File')),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.CODDetail')),
            ],
            options={
                'verbose_name': 'CODFiles',
                'verbose_name_plural': 'CODFiles',
            },
        ),
        migrations.AddField(
            model_name='coddetail',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Material', to='orders.CODMaterial', verbose_name='Materials'),
        ),
        migrations.AddField(
            model_name='coddetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.CODOrder'),
        ),
    ]
