# Generated by Django 3.0.4 on 2020-05-06 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='not_selected', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Detail title')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='amount')),
                ('note', models.TextField(verbose_name='detail note')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OperationCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100, verbose_name='Headline')),
                ('description', models.TextField(verbose_name='Description Order')),
                ('pdf_view', models.FileField(default='default.pdf', upload_to='pdf', verbose_name='Pdf order cover')),
                ('image_view', models.ImageField(default='default.jpg', upload_to='image_preview', verbose_name='Cover image')),
                ('other_files', models.FileField(default=None, upload_to='otherFiles')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Number of products')),
                ('lead_time', models.DateField(verbose_name='Deadline')),
                ('proposed_budget', models.CharField(choices=[('Unknown', 'Unknown'), ('Small, less than $ 100', 'Small, less than $ 100'), ('Medium, less than $ 1000', 'Medium, less than $ 1000'), ('High, over $ 1000', 'High, over $ 1000')], default='Unknown', max_length=40, verbose_name='Budget')),
                ('activity', models.BooleanField()),
                ('status', models.CharField(choices=[('In discussion', 'In discussion'), ('In work', 'In work'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='In discussion', max_length=20, verbose_name='Order status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='orders', to='orders.OperationCategories', verbose_name='Categories')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.AllCity', verbose_name='Order City')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('offer_description', models.TextField(verbose_name='Offer Description')),
                ('deadline', models.DateTimeField(verbose_name='Production time')),
                ('offer_price', models.PositiveIntegerField(verbose_name='Suggested price')),
                ('status', models.CharField(choices=[('In discussion', 'In discussion'), ('In work', 'In work'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='In discussion', max_length=20, verbose_name='Offer Status')),
                ('selected_offer', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='MassOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('other_files', models.FileField(upload_to='MassOrderArchive', verbose_name='Archive')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.ManyToManyField(blank=True, related_name='GroupOrder', to='orders.Detail', verbose_name='Detail')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files', verbose_name='File')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Order')),
            ],
            options={
                'verbose_name': 'Files',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(default=django.utils.timezone.now)),
                ('feet', models.TextField()),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Suggestion')),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='Detail', to='orders.OperationCategories', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='detail',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Material', verbose_name='Detail material'),
        ),
    ]
