# Generated by Django 3.0.4 on 2020-03-07 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=30)),
                ('lead_time', models.DateField()),
                ('proposed_budget', models.CharField(max_length=40)),
                ('activity', models.BooleanField()),
                ('status', models.CharField(max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
