# Generated by Django 3.0.4 on 2020-05-06 13:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouporder',
            name='author',
        ),
        migrations.RemoveField(
            model_name='grouporder',
            name='city',
        ),
        migrations.RemoveField(
            model_name='grouporder',
            name='detail',
        ),
        migrations.AlterField(
            model_name='order',
            name='categories',
            field=models.ManyToManyField(blank=True, default='Unknown', related_name='orders', to='orders.OperationCategories', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.PROTECT, to='orders.AllCity', verbose_name='Order City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(default='Description Order', verbose_name='Description Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lead_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(default='Headline', max_length=100, verbose_name='Headline'),
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.DeleteModel(
            name='GroupOrder',
        ),
    ]
