# Generated by Django 3.0.4 on 2020-05-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='file',
            field=models.FileField(default='default.jpg', upload_to='DetailFiles', verbose_name='DetailFile'),
        ),
    ]
