# Generated by Django 3.0.4 on 2020-05-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200506_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archive',
            field=models.ManyToManyField(null=True, to='orders.MassOrder'),
        ),
        migrations.AddField(
            model_name='order',
            name='group_order',
            field=models.BooleanField(default=False, verbose_name='Group?'),
        ),
    ]
