# Generated by Django 3.0.4 on 2020-03-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_operationcategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationcategories',
            old_name='categories',
            new_name='title',
        ),
    ]
