# Generated by Django 3.0.4 on 2020-03-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200310_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.OperationCategories'),
        ),
    ]
