# Generated by Django 3.0.4 on 2020-05-06 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200506_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='archive',
        ),
        migrations.AddField(
            model_name='order',
            name='archive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.MassOrder'),
        ),
    ]
