# Generated by Django 3.0.4 on 2020-03-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_files',
            field=models.ManyToManyField(blank=True, related_name='orders_file', to='orders.Files'),
        ),
    ]
