# Generated by Django 3.0.4 on 2020-05-06 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200506_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='orders.OperationCategories', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.AllCity', verbose_name='Order City'),
        ),
    ]
