# Generated by Django 3.0.4 on 2020-03-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200311_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_files',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
