# Generated by Django 3.0.4 on 2020-05-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200506_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='activity',
            field=models.BooleanField(default=False),
        ),
    ]
