# Generated by Django 3.0.4 on 2020-03-18 17:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Suggestion')),
            ],
        ),
    ]
