# Generated by Django 3.0.4 on 2020-05-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200506_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='archive',
            new_name='mass_order',
        ),
    ]
