# Generated by Django 3.0.4 on 2020-05-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200506_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='massorder',
            name='crushed_order',
            field=models.BooleanField(default=False),
        ),
    ]
