# Generated by Django 3.0.4 on 2020-05-07 01:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_massorder_crushed_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='massorder',
            name='activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='massorder',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.AllCity', verbose_name='Order City'),
        ),
        migrations.AddField(
            model_name='massorder',
            name='description',
            field=models.TextField(default='Description Order', verbose_name='Description Order'),
        ),
        migrations.AddField(
            model_name='massorder',
            name='lead_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Deadline'),
        ),
        migrations.AddField(
            model_name='massorder',
            name='proposed_budget',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Small, less than $ 100', 'Small, less than $ 100'), ('Medium, less than $ 1000', 'Medium, less than $ 1000'), ('High, over $ 1000', 'High, over $ 1000')], default='Unknown', max_length=40, verbose_name='Budget'),
        ),
        migrations.AddField(
            model_name='massorder',
            name='status',
            field=models.CharField(choices=[('In discussion', 'In discussion'), ('In work', 'In work'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='In discussion', max_length=20, verbose_name='Order status'),
        ),
        migrations.AddField(
            model_name='massorder',
            name='title',
            field=models.CharField(default='Headline', max_length=100, verbose_name='Headline'),
        ),
    ]
