# Generated by Django 3.0.4 on 2020-05-07 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_auto_20200507_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('offer_description', models.TextField(verbose_name='Offer Description')),
                ('deadline', models.DateTimeField(verbose_name='Production time')),
                ('offer_price', models.PositiveIntegerField(verbose_name='Suggested price')),
                ('status', models.CharField(choices=[('In discussion', 'In discussion'), ('In work', 'In work'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='In discussion', max_length=20, verbose_name='Offer Status')),
                ('selected_offer', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('mass_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.MassOrder')),
            ],
        ),
    ]
