# Generated by Django 3.0.4 on 2020-03-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200322_2307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='AllCity',
        ),
    ]
