# Generated by Django 3.0.4 on 2020-05-10 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0011_groupsuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CODCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CODCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='not_selected', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CODDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Number of products')),
                ('whose_material', models.CharField(choices=[('Author', 'Author'), ('Offeror', 'Offeror')], default='Offeror', max_length=10, verbose_name='Whose material?')),
                ('Note', models.TextField(default='You Note', verbose_name='You Note')),
                ('Deadline', models.DateField(verbose_name='Deadline')),
                ('Availability_date', models.DateField(null=True, verbose_name='Availability date')),
                ('image_cover', models.ImageField(default='default.jpg', upload_to='image_cover', verbose_name='Cover image')),
                ('Categories', models.ManyToManyField(blank=True, default='Default', related_name='CODDetail', to='orders.CODCategories', verbose_name='Categories')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='categories',
            field=models.ManyToManyField(blank=True, default='Default', related_name='orders', to='orders.OperationCategories', verbose_name='Categories'),
        ),
        migrations.RenameModel(
            old_name='Material',
            new_name='CODMaterial',
        ),
        migrations.CreateModel(
            name='CODOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='Headline', max_length=100, verbose_name='Headline')),
                ('description', models.TextField(default='Description Order', verbose_name='Description Order')),
                ('pdf_cover', models.FileField(default='default.pdf', upload_to='pdf_cover', verbose_name='Pdf order cover')),
                ('image_cover', models.ImageField(default='default.jpg', upload_to='image_cover', verbose_name='Cover image')),
                ('proposed_budget', models.CharField(choices=[('Unknown', 'Unknown'), ('Small', 'Small'), ('Medium', 'Medium'), ('High', 'High')], default='Unknown', max_length=40, verbose_name='Budget')),
                ('status', models.CharField(choices=[('Discussion', 'Discussion'), ('InWork', 'InWork'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='In discussion', max_length=20, verbose_name='Order status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.CODCity', verbose_name='Order City')),
            ],
        ),
        migrations.CreateModel(
            name='CODFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files', verbose_name='File')),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.CODDetail')),
            ],
            options={
                'verbose_name': 'DetailFiles',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.AddField(
            model_name='coddetail',
            name='material',
            field=models.ManyToManyField(blank=True, default='Default', related_name='Material', to='orders.CODMaterial', verbose_name='Materials'),
        ),
        migrations.AddField(
            model_name='coddetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.CODOrder'),
        ),
    ]
