# Generated by Django 3.0.4 on 2020-05-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200510_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codfile',
            options={'verbose_name': 'CODFiles', 'verbose_name_plural': 'CODFiles'},
        ),
    ]
