# Generated by Django 3.0.4 on 2020-05-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200510_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coddetail',
            name='image_cover',
            field=models.ImageField(default='default.jpg', upload_to='COD_Detail_image_cover', verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='codfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='COD_detail_files', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='codorder',
            name='image_cover',
            field=models.ImageField(default='default.jpg', upload_to='COD_order_image_cover', verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='codorder',
            name='pdf_cover',
            field=models.FileField(default='default.pdf', upload_to='COD_order_pdf_cover', verbose_name='Pdf order cover'),
        ),
    ]
