# Generated by Django 3.0.4 on 2020-03-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200322_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='proposed_budget',
            field=models.CharField(choices=[('NN', 'Неизвестный'), ('LT', 'Малый бюджет 20-50$'), ('MD', 'Средний бюджет 50-250$'), ('HT', 'Высокий бюджет 250$+')], default='NN', max_length=40),
        ),
    ]
