# Generated by Django 3.0.4 on 2020-05-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200510_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='codorder',
            name='archive',
            field=models.FileField(null=True, upload_to='COD_order_archive', verbose_name='Group Order Archive'),
        ),
    ]
