# Generated by Django 3.0.4 on 2020-03-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200322_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DIS', 'В обсуждении'), ('WK', 'В работe'), ('DE', 'Выполненый'), ('CD', 'Отменённый')], default='DIS', max_length=20),
        ),
    ]
