# Generated by Django 3.0.4 on 2020-05-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_codorder_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='codorder',
            name='group_status',
            field=models.BooleanField(default=False, verbose_name='Group Status'),
        ),
    ]
