# Generated by Django 3.0.4 on 2020-03-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200323_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='proposed_budget',
            field=models.CharField(choices=[('Неизвестный', 'Неизвестный'), ('Малый бюджет 20-50$', 'Малый бюджет 20-50$'), ('Средний бюджет 50-250$', 'Средний бюджет 50-250$'), ('Высокий бюджет 250$+', 'Высокий бюджет 250$+')], default='Неизвестный', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обсуждении', 'В обсуждении'), ('В работe', 'В работe'), ('Выполненый', 'Выполненый'), ('Отменённый', 'Отменённый')], default='В обсуждении', max_length=20),
        ),
    ]
