# Generated by Django 3.0.4 on 2020-05-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_codorder_group_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codorder',
            name='pdf_cover',
            field=models.FileField(default='COD_order_pdf_cover/default.pdf', upload_to='COD_order_pdf_cover', verbose_name='Pdf order cover'),
        ),
        migrations.AlterField(
            model_name='codorder',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Discussion', 'Discussion'), ('InWork', 'InWork'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Created', max_length=20, verbose_name='Order status'),
        ),
    ]
