# Generated by Django 3.0.4 on 2020-03-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200323_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='other_files',
            field=models.FileField(default='default.jpg', upload_to='otherFiles'),
        ),
        migrations.AddField(
            model_name='order',
            name='pdf_view',
            field=models.FileField(default='default.pdf', upload_to='pdf'),
        ),
    ]
