# Generated by Django 3.0.4 on 2020-03-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200324_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image_view',
            field=models.ImageField(default='default.jpg', upload_to='image_preview'),
        ),
    ]
