# Generated by Django 3.0.4 on 2020-05-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200511_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codorder',
            name='pdf_cover',
            field=models.FileField(default='default.pdf', upload_to='COD_order_pdf_cover', verbose_name='Pdf order cover'),
        ),
    ]
