# Generated by Django 3.0.4 on 2020-03-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_image_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image_view',
        ),
    ]
