# Generated by Django 3.0.4 on 2020-05-12 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200511_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coddetail',
            name='material',
        ),
        migrations.AddField(
            model_name='coddetail',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Material', to='orders.CODMaterial', verbose_name='Materials'),
        ),
    ]
