# Generated by Django 3.0.4 on 2020-03-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_order_image_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image_view',
            field=models.ImageField(default='default.jpg', upload_to='image_preview'),
        ),
    ]
