# Generated by Django 3.0.4 on 2020-05-12 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200512_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='order',
        ),
        migrations.AddField(
            model_name='file',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.CODDetail'),
        ),
    ]
