# Generated by Django 3.0.4 on 2020-03-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_image_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='proposed_budget',
            field=models.CharField(choices=[('Неизвестный', 'Неизвестный'), ('Малый бюджет 20-50$', 'Малый 20-50$'), ('Средний бюджет 50-250$', 'Средний 50-250$'), ('Высокий бюджет 250$+', 'Высокий 250$+')], default='Неизвестный', max_length=40),
        ),
    ]
