# Generated by Django 3.0.4 on 2020-03-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200326_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='proposed_budget',
            field=models.CharField(choices=[('Неизвестный', 'Неизвестный'), ('Малый 20-50$', 'Малый 20-50$'), ('Средний 50-250$', 'Средний 50-250$'), ('Высокий 250$+', 'Высокий 250$+')], default='Неизвестный', max_length=40),
        ),
    ]
