# Generated by Django 3.0.4 on 2020-05-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200512_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coddetail',
            name='Deadline',
            field=models.DateField(null=True, verbose_name='Deadline'),
        ),
    ]
