# Generated by Django 3.0.4 on 2020-03-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200326_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обсуждении', 'В обсуждении'), ('В работe', 'В работe'), ('Выполненый', 'Выполненый'), ('Отменённый', 'Отменённый'), ('Избранный', 'Избранный')], default='В обсуждении', max_length=20),
        ),
    ]
