# Generated by Django 3.0.4 on 2020-05-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200512_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='coddetail',
            name='name',
            field=models.CharField(default='Detail', max_length=100, verbose_name='Detail name'),
        ),
    ]
