# Generated by Django 3.0.4 on 2020-05-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_coddetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coddetail',
            name='image_cover',
            field=models.ImageField(default='COD_Detail_image_cover/default.jpg', upload_to='COD_Detail_image_cover', verbose_name='Cover image'),
        ),
    ]
