# Generated by Django 3.0.4 on 2020-05-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20200513_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='codorder',
            name='table',
            field=models.FileField(null=True, upload_to='COD_order_tables'),
        ),
    ]
