# Generated by Django 3.0.4 on 2020-03-28 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20200328_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Кол-во изделий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.OperationCategories', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.AllCity', verbose_name='Город заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(verbose_name='Описание заказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lead_time',
            field=models.DateField(verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='proposed_budget',
            field=models.CharField(choices=[('Неизвестный', 'Неизвестный'), ('Малый 20-50$', 'Малый 20-50$'), ('Средний 50-250$', 'Средний 50-250$'), ('Высокий 250$+', 'Высокий 250$+')], default='Неизвестный', max_length=40, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обсуждении', 'В обсуждении'), ('В работe', 'В работe'), ('Выполненый', 'Выполненый'), ('Отменённый', 'Отменённый'), ('Избранный', 'Избранный')], default='В обсуждении', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files', verbose_name='Файл')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Order')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
