# Generated by Django 3.0.4 on 2020-03-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20200328_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pdf_view',
            field=models.FileField(default='default.pdf', upload_to='pdf', verbose_name='Обложка заказа'),
        ),
    ]
