# Generated by Django 3.0.4 on 2020-05-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_codorder_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='coddetail',
            name='dxf',
            field=models.FileField(blank=True, null=True, upload_to='COD_detail_files', verbose_name='DXF'),
        ),
        migrations.AddField(
            model_name='coddetail',
            name='part',
            field=models.FileField(blank=True, null=True, upload_to='COD_detail_files', verbose_name='PART'),
        ),
        migrations.AddField(
            model_name='coddetail',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='COD_detail_files', verbose_name='PDF'),
        ),
        migrations.AddField(
            model_name='coddetail',
            name='step',
            field=models.FileField(blank=True, null=True, upload_to='COD_detail_files', verbose_name='STEP'),
        ),
    ]
