# Generated by Django 3.0.4 on 2020-03-31 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20200328_0945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
