# Generated by Django 3.0.4 on 2020-04-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image_view',
            field=models.ImageField(default='default.jpg', upload_to='image_preview', verbose_name='Обложка заказа image'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pdf_view',
            field=models.FileField(default='default.pdf', upload_to='pdf', verbose_name='Обложка заказа pdf'),
        ),
    ]
