# Generated by Django 3.0.4 on 2020-04-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20200401_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.CharField(choices=[('В обсуждении', 'В обсуждении'), ('В работe', 'В работe'), ('Выполнено', 'Выполнено'), ('Отклонено', 'Отклонено'), ('Архив', 'Архив')], default='В обсуждении', max_length=20, verbose_name='Статус предложения'),
        ),
    ]
