# Generated by Django 3.0.4 on 2020-04-12 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20200409_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_create',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
