# Generated by Django 3.0.4 on 2020-04-12 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20200412_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
