# Generated by Django 3.0.4 on 2020-04-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20200412_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обсуждении', 'В обсуждении'), ('В работe', 'В работe'), ('Выполненый', 'Выполненый'), ('Отменённый', 'Отменённый')], default='В обсуждении', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.CharField(choices=[('В обсуждении', 'В обсуждении'), ('В работe', 'В работe'), ('Выполнено', 'Выполнено'), ('Отклонено', 'Отклонено')], default='В обсуждении', max_length=20, verbose_name='Статус предложения'),
        ),
    ]
