# Generated by Django 3.0.4 on 2020-04-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20200412_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
