# Generated by Django 3.0.4 on 2020-04-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_suggestion_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='other_files',
            field=models.FileField(default=None, upload_to='otherFiles'),
        ),
    ]
