# Generated by Django 3.0.4 on 2020-04-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20200414_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='feedback',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='deadline',
            field=models.DateTimeField(verbose_name='Сроки изготовления'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='offer_description',
            field=models.TextField(verbose_name='Описание предложения'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='offer_price',
            field=models.PositiveIntegerField(verbose_name='Предлагаемая цена'),
        ),
    ]
