# Generated by Django 3.0.4 on 2020-04-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_auto_20200414_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='feedback',
        ),
    ]
