# Generated by Django 3.0.4 on 2020-04-15 09:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_remove_suggestion_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(default=django.utils.timezone.now)),
                ('feet', models.TextField()),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Suggestion')),
            ],
        ),
    ]
