# Generated by Django 3.0.4 on 2020-04-15 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Suggestion'),
        ),
    ]
