# Generated by Django 3.0.4 on 2020-04-29 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_massorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Files', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='massorder',
            name='other_files',
            field=models.FileField(upload_to='MassOrderArchive', verbose_name='Archive'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Number of products'),
        ),
        migrations.AlterField(
            model_name='order',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.OperationCategories', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.AllCity', verbose_name='Order City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(verbose_name='Description Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='image_view',
            field=models.ImageField(default='default.jpg', upload_to='image_preview', verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lead_time',
            field=models.DateField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pdf_view',
            field=models.FileField(default='default.pdf', upload_to='pdf', verbose_name='Pdf order cover'),
        ),
        migrations.AlterField(
            model_name='order',
            name='proposed_budget',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Small, less than $ 100', 'Small, less than $ 100'), ('Medium, less than $ 1000', 'Medium, less than $ 1000'), ('High, over $ 1000', 'High, over $ 1000')], default='Unknown', max_length=40, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In discussion', 'In discussion'), ('In work', 'In work'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='In discussion', max_length=20, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Headline'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='deadline',
            field=models.DateTimeField(verbose_name='Production time'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='offer_description',
            field=models.TextField(verbose_name='Offer Description'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='offer_price',
            field=models.PositiveIntegerField(verbose_name='Suggested price'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.CharField(choices=[('In discussion', 'In discussion'), ('In work', 'In work'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='In discussion', max_length=20, verbose_name='Offer Status'),
        ),
    ]
