# Generated by Django 3.0.4 on 2020-03-31 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_delete_message'),
        ('chat', '0002_auto_20200331_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
        migrations.AddField(
            model_name='message',
            name='suggestion',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='orders.Suggestion', verbose_name='Предложение'),
        ),
    ]
