# Generated by Django 3.0.4 on 2020-03-31 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20200331_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='members',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
