# Generated by Django 3.0.4 on 2020-03-31 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_message_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='members',
        ),
        migrations.AddField(
            model_name='message',
            name='member',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
    ]
