# Generated by Django 3.0.4 on 2020-05-10 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0012_auto_20200510_1627'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CODSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('offer_description', models.TextField(verbose_name='Offer Description')),
                ('deadline', models.DateTimeField(verbose_name='Production time')),
                ('offer_price', models.PositiveIntegerField(verbose_name='Suggested price')),
                ('status', models.CharField(choices=[('Discussion', 'Discussion'), ('InWork', 'InWork'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Discussion', max_length=20, verbose_name='Offer Status')),
                ('rating', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.CODOrder')),
            ],
        ),
        migrations.CreateModel(
            name='CODFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(default=django.utils.timezone.now)),
                ('feet', models.TextField()),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestions.CODSuggestion')),
            ],
        ),
    ]
