# Generated by Django 3.0.4 on 2020-05-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CADFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='otherFiles')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageFile', models.ImageField(null=True, upload_to='SiteImage', verbose_name='Картинки')),
                ('heading', models.CharField(max_length=240, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
