# Generated by Django 3.0.4 on 2020-04-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagefiles',
            name='ImageFile',
            field=models.ImageField(null=True, upload_to='SiteImage', verbose_name='Картинки'),
        ),
    ]
