# Generated by Django 3.0.4 on 2020-05-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_cadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadfile',
            name='file',
            field=models.FileField(upload_to='otherFiles'),
        ),
    ]
