# Generated by Django 3.0.4 on 2020-04-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_auto_20200402_1042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePageFiles',
            new_name='HomePageFile',
        ),
    ]
