# Generated by Django 3.0.4 on 2020-04-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_auto_20200402_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagefile',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homepagefile',
            name='heading',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
