# Generated by Django 3.0.4 on 2020-05-30 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStripe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(blank=True, max_length=120, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('rating', models.PositiveIntegerField(default=0)),
                ('notifications', models.BooleanField(default=False, verbose_name='Receive notifications?')),
                ('notifi_account', models.BooleanField(default=False, verbose_name='Notifications to the office?')),
                ('notifi_email', models.BooleanField(default=False, verbose_name='Email notifications?')),
                ('notifi_sms', models.BooleanField(default=False, verbose_name='SMS notifications')),
                ('notifi_news', models.BooleanField(default=False, verbose_name='News?')),
                ('notifi_articles', models.BooleanField(default=False, verbose_name='Articles?')),
                ('notifi_updates', models.BooleanField(default=False, verbose_name='Updates?')),
                ('timing', models.CharField(choices=[('Never', '0 hours'), ('Each hour', '1 hour'), ('Every 3 hours', '3 hours'), ('Every 6 hours', '6 hours'), ('Every 12 hours', '12 hours'), ('Every 24 hours', '24 hours')], default='Never', max_length=30, verbose_name='Update frequency')),
                ('categories', models.ManyToManyField(blank=True, related_name='profile', to='orders.OperationCategories', verbose_name='Categories for notifications')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='CompanyName', verbose_name='Abbreviated company name')),
                ('edrpou', models.CharField(max_length=10, verbose_name='EDRPOU')),
                ('officialName', models.TextField(default='OfficialCompanyName', verbose_name='The official name of the company')),
                ('address', models.TextField(default='CompanyAddress', verbose_name='Company Registration Address')),
                ('mainPerson', models.CharField(default='CompanyMainPerson', max_length=255, verbose_name='Head of the organization')),
                ('occupation', models.TextField(default='CompanyOccupation', verbose_name='The main activity of the organization')),
                ('status', models.CharField(default='CompanyStatus', max_length=255, verbose_name='Organization Status')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
