# Generated by Django 3.0.4 on 2020-04-13 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20200412_1259'),
        ('users', '0002_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_rating',
            name='suggestion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.Suggestion'),
        ),
    ]
