# Generated by Django 3.0.4 on 2020-04-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_rating_suggestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Rating',
        ),
    ]
