# Generated by Django 3.0.4 on 2020-04-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
