# Generated by Django 3.0.4 on 2020-04-15 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_profile_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='CompanyName', verbose_name='Сокращенное название компании')),
                ('edrpou', models.CharField(max_length=10, verbose_name='ЕДРПОУ')),
                ('officialName', models.TextField(default='OfficialCompanyName', verbose_name='Официальное название компании')),
                ('address', models.TextField(default='CompanyAddress', verbose_name='Адрес регистрации компании')),
                ('mainPerson', models.CharField(default='CompanyMainPerson', max_length=255, verbose_name='Руководитель организации')),
                ('occupation', models.TextField(default='CompanyOccupation', verbose_name='Основной вид деятельности организации')),
                ('status', models.CharField(default='CompanyStatus', max_length=255, verbose_name='Состояние организации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
