# Generated by Django 3.0.4 on 2020-04-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200415_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='mainPerson',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='officialName',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='status',
        ),
    ]
