# Generated by Django 3.0.4 on 2020-04-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200415_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='user',
            new_name='user_name',
        ),
    ]
