# Generated by Django 3.0.4 on 2020-04-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200415_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(default='CompanyAddress', verbose_name='Адрес регистрации компании'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='mainPerson',
            field=models.CharField(default='CompanyMainPerson', max_length=255, verbose_name='Руководитель организации'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='name',
            field=models.TextField(default='CompanyName', verbose_name='Сокращенное название компании'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='occupation',
            field=models.TextField(default='CompanyOccupation', verbose_name='Основной вид деятельности организации'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='officialName',
            field=models.TextField(default='OfficialCompanyName', verbose_name='Официальное название компании'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='status',
            field=models.CharField(default='CompanyStatus', max_length=255, verbose_name='Состояние организации'),
        ),
    ]
