# Generated by Django 3.0.4 on 2020-04-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200415_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifi_account',
            field=models.BooleanField(default=False, verbose_name='Уведомления в кабинет?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notifi_articles',
            field=models.BooleanField(default=False, verbose_name='Статьи?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notifi_email',
            field=models.BooleanField(default=False, verbose_name='Уведомления на почту?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notifi_news',
            field=models.BooleanField(default=False, verbose_name='Новости?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notifi_sms',
            field=models.BooleanField(default=False, verbose_name='Уведомления по СМС'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notifi_updates',
            field=models.BooleanField(default=False, verbose_name='Обновления?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.BooleanField(default=False, verbose_name='Получать уведомления?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='timing',
            field=models.CharField(choices=[('Никогда', '0 часов'), ('Каждый час', '1 час'), ('Каждые 3 часа', '3 часа'), ('Каждые 6 часов', '6 часов'), ('Каждые 12 часов', '12 часов'), ('Каждые 24 часа', '24 часа')], default='Никогда', max_length=30, verbose_name=''),
        ),
    ]
