# Generated by Django 3.0.4 on 2020-04-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_massorder'),
        ('users', '0012_auto_20200419_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='profile', to='orders.OperationCategories', verbose_name='Категории для уведомлений'),
        ),
    ]
