# Generated by Django 3.0.4 on 2020-04-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_key',
            field=models.CharField(default=123456789100, max_length=12, verbose_name='Ключ активации'),
        ),
        migrations.AddField(
            model_name='profile',
            name='authorization',
            field=models.BooleanField(default=False, verbose_name='Статус авторизации'),
        ),
    ]
