# Generated by Django 3.0.4 on 2020-04-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_massorder'),
        ('account', '0002_email_max_length'),
        ('chat', '0005_auto_20200331_1153'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0016_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
