# Generated by Django 3.0.4 on 2020-04-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_auto_20200429_1940'),
        ('users', '0018_userstripe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(default='CompanyAddress', verbose_name='Company Registration Address'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='edrpou',
            field=models.CharField(max_length=10, verbose_name='EDRPOU'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='mainPerson',
            field=models.CharField(default='CompanyMainPerson', max_length=255, verbose_name='Head of the organization'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.TextField(default='CompanyName', verbose_name='Abbreviated company name'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='occupation',
            field=models.TextField(default='CompanyOccupation', verbose_name='The main activity of the organization'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='officialName',
            field=models.TextField(default='OfficialCompanyName', verbose_name='The official name of the company'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='status',
            field=models.CharField(default='CompanyStatus', max_length=255, verbose_name='Organization Status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='profile', to='orders.OperationCategories', verbose_name='Categories for notifications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notifi_account',
            field=models.BooleanField(default=False, verbose_name='Notifications to the office?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notifi_articles',
            field=models.BooleanField(default=False, verbose_name='Articles?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notifi_email',
            field=models.BooleanField(default=False, verbose_name='Email notifications?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notifi_news',
            field=models.BooleanField(default=False, verbose_name='News?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notifi_sms',
            field=models.BooleanField(default=False, verbose_name='SMS notifications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notifi_updates',
            field=models.BooleanField(default=False, verbose_name='Updates?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notifications',
            field=models.BooleanField(default=False, verbose_name='Receive notifications?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timing',
            field=models.CharField(choices=[('Never', '0 hours'), ('Each hour', '1 hour'), ('Every 3 hours', '3 hours'), ('Every 6 hours', '6 hours'), ('Every 12 hours', '12 hours'), ('Every 24 hours', '24 hours')], default='Never', max_length=30, verbose_name='Update frequency'),
        ),
    ]
